# Generated by Django 4.0.6 on 2022-08-02 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('created_date', models.DateTimeField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
